### PR TITLE
Make it possible for rproxy to stop advertising itself.

### PR DESCRIPTION
**Pull request by Lukasa**
It's frankly none of the client's business whether I'm using rproxy or not. I'd like to be able to switch this off. =)

### CODE REVIEW

**Comment by hawkowl** [comment]
This wouldn't actually work because nothing passes it this flag :P

**Comment by Lukasa** [comment]
Depends. I was using the RProxyResource directly.

**Comment by hawkowl** [comment]
PLS REMERGE SO I CAN MERGERATEIFY

**Comment by Lukasa** [comment]
Done.

**Comment by hawkowl** [comment]
AND SO THE LUKASA-HAWKIE SOFTWARE FORK GAP CLOSES FURTHER

**Pull request merged**
